### ISSUE TITLE
Navigation automatisch erstellen

### ISSUE THREAD

**Issue by wobintosh** [wobintosh/fami-einfuehrung#2]
Statt der bisherigen, manuell erstellten Navigation, solte diese automatisch erstellt werden. 

Erfordert das Plugin `awesome-pages` und eine Datei `.pages` neben der Config-YML:

```
nav:
    - Einführung: einfuehrung.md
        - ...
    - IT:
        - ...
    - Nachschlagewerke:
        - ...
```

An Stelle der Punkte füllt das Plugin automatisch Unterverzeichnisse & Dateien ein.
